In [5]:
import numpy as np

In [6]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[1,2,3]])

In [7]:
print("Matrix A:\n",A)
print("Matrix B:\n",B)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[7 8 9]
 [1 2 3]]


# **Additional And Subtraction**

In [10]:
print("\nA + B =\n",A + B)
print("\nA - B =\n",A - B)


A + B =
 [[ 8 10 12]
 [ 5  7  9]]

A - B =
 [[-6 -6 -6]
 [ 3  3  3]]


# **Scalar Multiplication**

In [11]:
print("\n2 * A =\n",2*A)


2 * A =
 [[ 2  4  6]
 [ 8 10 12]]


# **Transponse**

In [12]:
print("\nTransponse ofA:\n",A.T)


Transponse ofA:
 [[1 4]
 [2 5]
 [3 6]]


#  **Matrix Multiplication**
## **For multiplication, inner dimensions must match**

In [13]:
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [14]:
print("\nMatrix C:\n", C)
print("\nA (2x3) * C (3x2) =\n", A.dot(C))


Matrix C:
 [[1 2]
 [3 4]
 [5 6]]

A (2x3) * C (3x2) =
 [[22 28]
 [49 64]]


# **Identity Matrix**


In [15]:
I = np.eye(3)
print("\nIdentity Matrix (3x3):\n", I)


Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# **Inverse of a Square Matrix**

In [16]:
M = np.array([[4, 7],
              [2, 6]])
print("\nMatrix M:\n", M)
print("Determinant of M:", np.linalg.det(M))

if np.linalg.det(M) != 0:
    inv_M = np.linalg.inv(M)
    print("\nInverse of M:\n", inv_M)
    print("\nM * M^-1 =\n", M.dot(inv_M))


Matrix M:
 [[4 7]
 [2 6]]
Determinant of M: 10.000000000000002

Inverse of M:
 [[ 0.6 -0.7]
 [-0.2  0.4]]

M * M^-1 =
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
