# 📝 Dot Product (Vectors)

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [3]:
print(f"Vector a: {a}")
print(f"Vector b: {b}")

Vector a: [1 2 3]
Vector b: [4 5 6]


## Dot product

In [4]:
dot_ab = np.dot(a, b)
print(f"\nDot Product (a . b) = {dot_ab}")


Dot Product (a . b) = 32


# 📝 Dot Product (Matrix Multiplication Form)

## Define matrices

In [5]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

In [6]:
print(f"Matrix A:\n {A}")
print(f"Matrix B:\n {B}")

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]


## Dot product (matrix multiplication)

In [8]:
C = np.dot(A, B)
print(f"\nA . B=\n{C}")


A . B=
[[19 22]
 [43 50]]


## Transpose

In [9]:
print("\nTranspose of A:\n", A.T)


Transpose of A:
 [[1 3]
 [2 4]]


## Double transpose = original

In [10]:
print("\n(A^T)^T =\n", (A.T).T)


(A^T)^T =
 [[1 2]
 [3 4]]
